Add argument to additional options to argoCD
paritytech/argocd-deployment-action pull request #2
Opened 2024-10-23 10:09 UTC by alvicsam

cc https://github.com/paritytech/ci_cd/issues/1044

2024-10-23 11:47 UTC, mutantcornholio approved these changes

2024-10-23 12:13 UTC, mordamax requested changes
shouldn't be needed (at least for your use-case) as `app_packages` allows to pass the apps and tags

2024-10-24 08:21 UTC, alvicsam commented
Yep, existing option is enough

2024-10-28 10:28 UTC, alvicsam commented
Reopening because it still needs for things like [this](https://github.com/paritytech/substrate-telemetry/blob/master/.gitlab-ci.yml#L116-L119)

2024-10-28 10:34 UTC, mordamax approved these changes

2024-10-28 10:34 UTC, merged